version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - mtdvlpr
    assignees:
      - mtdvlpr
    commit-message:
      prefix: chore
      include: scope
    ignore:
      - dependency-name: 'webpack'
        update-types: ['version-update:semver-major']
  # Fetch and update latest `composer` packages
  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - mtdvlpr
    assignees:
      - mtdvlpr
    commit-message:
      prefix: chore
      include: scope
